use serde::Serialize;

use crate::lz77;
use crate::rom::{read_ptr, read_u16_le, read_u32_le, GameVersion, RomOffsets};
use crate::tiles::{decode_4bpp_tile, decode_palette, render_tile_rgba};

/// Bytes per 4bpp tile
const TILE_BYTES: usize = 32;

/// Max frames we'll decode per sprite (safety limit)
const MAX_FRAMES: usize = 24;

/// GBA sprites have 3 directions (down/up/left); right is left mirrored
const ANIM_FRAMES_PER_DIR: usize = 3;

/// A decoded overworld sprite with all animation frames
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DecodedSprite {
    pub graphics_id: u16,
    pub width: u16,
    pub height: u16,
    pub frames: Vec<SpriteFrame>,
}

/// A single animation frame
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SpriteFrame {
    pub direction: String,
    pub frame_index: u8,
    pub pixels: Vec<u8>, // RGBA
}

/// Decode an overworld sprite by graphics ID.
///
/// The graphics table is a pointer table: each entry is a 4-byte GBA pointer
/// to an ObjectEventGraphicsInfo struct (0x24 bytes).
///
/// GBA overworld sprites typically have 9 frames: 3 per direction (down/up/left).
/// Right-facing frames are generated by mirroring left-facing frames.
pub fn decode_overworld_sprite(
    data: &[u8],
    version: GameVersion,
    graphics_id: u16,
) -> Option<DecodedSprite> {
    let offsets = RomOffsets::for_game(version);
    let gfx_table = offsets.overworld_graphics_table;

    // The table is an array of pointers — follow indirection
    let ptr_offset = gfx_table + (graphics_id as usize) * 4;
    let info_ptr = read_ptr(data, ptr_offset)?;
    if info_ptr + 0x24 > data.len() {
        return None;
    }

    // Parse ObjectEventGraphicsInfo fields
    let _tile_tag = read_u16_le(data, info_ptr)?;
    let palette_tag = read_u16_le(data, info_ptr + 2)?;
    let _reflection_pal_tag = read_u16_le(data, info_ptr + 4)?;
    let _size_field = read_u16_le(data, info_ptr + 6)?;
    let width = read_u16_le(data, info_ptr + 8)? as usize;
    let height = read_u16_le(data, info_ptr + 0x0A)? as usize;

    if width == 0 || height == 0 || width > 64 || height > 64 {
        return None;
    }

    // Images pointer at offset 0x1C in the struct
    let images_ptr = read_ptr(data, info_ptr + 0x1C)?;

    // Count frames by scanning SpriteFrameImage entries (8 bytes each)
    // Each entry: { data_ptr: u32, size: u16, padding: u16 }
    let mut frame_count = 0;
    loop {
        let entry_off = images_ptr + frame_count * 8;
        if entry_off + 8 > data.len() {
            break;
        }
        match read_ptr(data, entry_off) {
            Some(_) => frame_count += 1,
            None => break,
        }
        if frame_count >= MAX_FRAMES {
            break;
        }
    }
    if frame_count == 0 {
        return None;
    }

    // Read the base sprite data from the first frame entry
    let base_data_ptr = read_ptr(data, images_ptr)?;
    let tiles_per_frame = (width / 8) * (height / 8);
    let bytes_per_frame = tiles_per_frame * TILE_BYTES;
    let total_data_size = frame_count * bytes_per_frame;

    let tile_data = if lz77::is_lz77(data, base_data_ptr) {
        lz77::decompress(data, base_data_ptr)?
    } else {
        if base_data_ptr + total_data_size > data.len() {
            return None;
        }
        data[base_data_ptr..base_data_ptr + total_data_size].to_vec()
    };

    // Re-check actual frames from decompressed data
    let actual_frames = if bytes_per_frame > 0 {
        (tile_data.len() / bytes_per_frame).min(frame_count)
    } else {
        0
    };

    let palette = find_sprite_palette(data, version, palette_tag);
    let frame_pixel_count = width * height * 4;

    // Decode each frame into RGBA pixels
    let mut raw_frames: Vec<Vec<u8>> = Vec::new();
    for frame_idx in 0..actual_frames {
        let frame_offset = frame_idx * bytes_per_frame;
        let mut frame_pixels = vec![0u8; frame_pixel_count];

        let tiles_x = width / 8;
        let tiles_y = height / 8;

        for ty in 0..tiles_y {
            for tx in 0..tiles_x {
                let tile_idx = ty * tiles_x + tx;
                let tile_offset = frame_offset + tile_idx * TILE_BYTES;

                if tile_offset + TILE_BYTES > tile_data.len() {
                    continue;
                }

                if let Some(indices) = decode_4bpp_tile(&tile_data[tile_offset..]) {
                    let tile_rgba = render_tile_rgba(&indices, &palette);

                    for row in 0..8 {
                        for col in 0..8 {
                            let src = (row * 8 + col) * 4;
                            let dst_x = tx * 8 + col;
                            let dst_y = ty * 8 + row;
                            let dst = (dst_y * width + dst_x) * 4;

                            if dst + 3 < frame_pixels.len() {
                                frame_pixels[dst] = tile_rgba[src];
                                frame_pixels[dst + 1] = tile_rgba[src + 1];
                                frame_pixels[dst + 2] = tile_rgba[src + 2];
                                frame_pixels[dst + 3] = tile_rgba[src + 3];
                            }
                        }
                    }
                }
            }
        }
        raw_frames.push(frame_pixels);
    }

    // Map raw frames to direction + anim frame
    // Standard layout: frames 0-2 = down, 3-5 = up, 6-8 = left
    // Right = horizontally mirrored left
    let dir_names = ["down", "up", "left"];
    let mut frames = Vec::new();

    for (i, pixels) in raw_frames.iter().enumerate() {
        let dir_idx = i / ANIM_FRAMES_PER_DIR;
        let anim_frame = i % ANIM_FRAMES_PER_DIR;

        if dir_idx < dir_names.len() {
            frames.push(SpriteFrame {
                direction: dir_names[dir_idx].to_string(),
                frame_index: anim_frame as u8,
                pixels: pixels.clone(),
            });
        }
    }

    // Generate mirrored "right" frames from "left" frames
    let left_start = 2 * ANIM_FRAMES_PER_DIR; // frame index 6
    for anim in 0..ANIM_FRAMES_PER_DIR {
        let left_idx = left_start + anim;
        if left_idx < raw_frames.len() {
            let mirrored = mirror_frame_horizontal(&raw_frames[left_idx], width, height);
            frames.push(SpriteFrame {
                direction: "right".to_string(),
                frame_index: anim as u8,
                pixels: mirrored,
            });
        }
    }

    Some(DecodedSprite {
        graphics_id,
        width: width as u16,
        height: height as u16,
        frames,
    })
}

/// Horizontally mirror a frame's RGBA pixel buffer.
fn mirror_frame_horizontal(pixels: &[u8], width: usize, height: usize) -> Vec<u8> {
    let mut out = vec![0u8; pixels.len()];
    for y in 0..height {
        for x in 0..width {
            let src = (y * width + x) * 4;
            let dst = (y * width + (width - 1 - x)) * 4;
            if src + 3 < pixels.len() && dst + 3 < out.len() {
                out[dst] = pixels[src];
                out[dst + 1] = pixels[src + 1];
                out[dst + 2] = pixels[src + 2];
                out[dst + 3] = pixels[src + 3];
            }
        }
    }
    out
}

/// Find a sprite palette by scanning the ROM for a SpritePalette table entry
/// matching the given palette tag.
///
/// SpritePalette entries are 8 bytes: { data_ptr: u32, tag: u16, padding: u16 }
/// We search near the overworld graphics table for entries with matching tags.
fn find_sprite_palette(
    data: &[u8],
    version: GameVersion,
    palette_tag: u16,
) -> [[u8; 4]; 16] {
    let offsets = RomOffsets::for_game(version);
    let base = offsets.overworld_graphics_table;

    // Search within ±256KB of the graphics table
    let search_start = base.saturating_sub(0x10000) & !3;
    let search_end = (base + 0x40000).min(data.len().saturating_sub(8));

    let tag_le = palette_tag.to_le_bytes();

    let mut off = search_start;
    while off + 8 <= search_end {
        // Check if tag at offset+4 matches
        if data[off + 4] == tag_le[0] && data[off + 5] == tag_le[1] {
            // Verify data pointer looks like a valid GBA pointer
            if let Some(raw) = read_u32_le(data, off) {
                if (raw & 0xFE00_0000) == 0x0800_0000 {
                    // Validate this is actually a palette table by checking neighbors
                    if is_palette_table_entry(data, off.wrapping_sub(8))
                        || is_palette_table_entry(data, off + 8)
                    {
                        if let Some(pal_off) = read_ptr(data, off) {
                            if let Some(pal) = decode_palette(data, pal_off) {
                                return pal;
                            }
                        }
                    }
                }
            }
        }
        off += 4;
    }

    // Fallback: grayscale
    default_grayscale_palette()
}

/// Check if an offset looks like a SpritePalette table entry.
fn is_palette_table_entry(data: &[u8], off: usize) -> bool {
    if off + 8 > data.len() {
        return false;
    }
    if let Some(raw) = read_u32_le(data, off) {
        // Null pointer = sentinel (valid end-of-table marker)
        if raw == 0 {
            return true;
        }
        // Valid GBA pointer with reasonable tag range (0x1000-0x2000)
        if (raw & 0xFE00_0000) == 0x0800_0000 {
            if let Some(tag) = read_u16_le(data, off + 4) {
                return (0x1000..=0x2000).contains(&tag);
            }
        }
    }
    false
}

fn default_grayscale_palette() -> [[u8; 4]; 16] {
    let mut palette = [[0u8; 4]; 16];
    palette[0] = [0, 0, 0, 0];
    for i in 1..16 {
        let v = ((i as u32 * 255) / 15) as u8;
        palette[i] = [v, v, v, 255];
    }
    palette
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn npc_dimensions() {
        // Standard NPC: 16×32 = 8 tiles per frame, 2048 RGBA bytes per frame
        let tiles = (16 / 8) * (32 / 8);
        assert_eq!(tiles, 8);
        assert_eq!(16 * 32 * 4, 2048);
    }

    #[test]
    fn mirror_frame() {
        // 2×1 pixel frame: red on left, blue on right
        let pixels = vec![255, 0, 0, 255, 0, 0, 255, 255];
        let mirrored = mirror_frame_horizontal(&pixels, 2, 1);
        // After mirror: blue on left, red on right
        assert_eq!(mirrored[0], 0);   // blue R
        assert_eq!(mirrored[2], 255); // blue B
        assert_eq!(mirrored[4], 255); // red R
        assert_eq!(mirrored[6], 0);   // red B
    }

    #[test]
    fn grayscale_palette_fallback() {
        let palette = default_grayscale_palette();
        assert_eq!(palette[0][3], 0); // transparent
        assert_eq!(palette[15][0], 255); // white
        assert_eq!(palette[15][3], 255); // opaque
    }

    #[test]
    fn palette_table_entry_validation() {
        // Valid entry: GBA pointer + tag in range
        let mut data = vec![0u8; 16];
        // Pointer: 0x08100000
        data[0] = 0x00;
        data[1] = 0x00;
        data[2] = 0x10;
        data[3] = 0x08;
        // Tag: 0x1100
        data[4] = 0x00;
        data[5] = 0x11;
        assert!(is_palette_table_entry(&data, 0));

        // Null sentinel is valid
        let zeros = vec![0u8; 16];
        assert!(is_palette_table_entry(&zeros, 0));

        // Invalid: tag out of range
        let mut bad = data.clone();
        bad[4] = 0x00;
        bad[5] = 0x00; // tag = 0
        assert!(!is_palette_table_entry(&bad, 0));
    }
}
